### ISSUE TITLE
LF exercises with traces are not saved properly

### ISSUE THREAD

**Issue by champoll** [nyusemantics/LambdaCalculator#18]
When solving an LF exercise in the student edition of the lambda calculator and then saving the file and reopening it, if the exercise contains traces then it is displayed without any calculations on nonterminal nodes, even if the student edition user has computed the meaning of all the nonterminal nodes in the tree all the way up to the root and thus completed the exercise. 

To reproduce, solve exercises in attached file placement_test.txt and then save and reopen. Trees 6 and 9-13 are labeled as not solved even if they were previously solved. 
<img width="1280" alt="placement_test" src="https://user-images.githubusercontent.com/7155025/35528385-afe0af58-04fb-11e8-88ff-c4d26a942e04.png">

[placement_test.txt](https://github.com/nyusemantics/LambdaCalculator/files/1674849/placement_test.txt)

**Comment by alexwarstadt** [comment]
The issue was with _loading_ exercises with traces, not with saving them. In TreeExerciseWidget, buildTree recursively constructs the tree from the serialization. If the user had provided a denotation for a trace, the method onUserChangedNodeMeaning would clear the meaning state of the all the parent nodes at the block starting line 402. 

I'm not sure what the intent of this block is in general, but if it is avoided when the node is a trace, the result is as intended.
