### ISSUE TITLE
Product Types (again)

### ISSUE THREAD

**Issue by a-s-davies** [nyusemantics/LambdaCalculator#21]
Hi.

For some reason every time I try to make an expression a product type, I get this error message: 
The expression is ambiguous. Add some angle brackets <>.. Pos: 8

[I got this for the folllowing expression in the scratchpad: λG_<e × e, t>.G(e, e)]

I'm not sure what's going wrong. Probably something very simple. Any ideas?

**Comment by aualsop** [comment]
The error message appears because product types are defined using the `*` symbol. There's one additional issue with your expression, though. The arguments of G must be explicitly typed in the Scratchpad. This can be done by specifying the type of `e` as below: 

`λG_<e*e, t>.G(e_e, e_e)`

Alternatively, you can use the default constants and variables in the Scratchpad:

`λG_<e*e, t>.G(j, y)`
